// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AliasSnapshotData, AliasSnapshotErrors, AliasSnapshotResponses, AuthorizeData, AuthorizeErrors, AuthorizeResponses, BatchGetSandboxesData, BatchGetSandboxesErrors, BatchGetSandboxesResponses, BatchGetSnapshotsData, BatchGetSnapshotsErrors, BatchGetSnapshotsResponses, CreateSandboxData, CreateSandboxErrors, CreateSandboxResponses, CreateSnapshotData, CreateSnapshotErrors, CreateSnapshotResponses, DeleteSnapshotAliasData, DeleteSnapshotAliasErrors, DeleteSnapshotAliasResponses, GetSandboxData, GetSandboxErrors, GetSandboxResponses, GetSnapshotByAliasData, GetSnapshotByAliasErrors, GetSnapshotByAliasResponses, GetSnapshotData, GetSnapshotErrors, GetSnapshotResponses, IssueContainerRegistryCredentialData, IssueContainerRegistryCredentialErrors, IssueContainerRegistryCredentialResponses, ListSandboxesData, ListSandboxesErrors, ListSandboxesResponses, ListSnapshotAliasesData, ListSnapshotAliasesErrors, ListSnapshotAliasesResponses, ListSnapshotsData, ListSnapshotsErrors, ListSnapshotsResponses, RetireSnapshotData, RetireSnapshotErrors, RetireSnapshotResponses, TerminateSandboxData, TerminateSandboxErrors, TerminateSandboxResponses, WaitForSandboxData, WaitForSandboxErrors, WaitForSandboxResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authorize access to a project or container registry project
 */
export const authorize = <ThrowOnError extends boolean = false>(options: Options<AuthorizeData, ThrowOnError>) => {
    return (options.client ?? client).post<AuthorizeResponses, AuthorizeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/authorize',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Issue a container registry credential for the authenticated user
 * Returns credentials (username, password, registry URL) for authenticating with the container registry. The registry URL includes the user's namespace path derived from their project ID.
 *
 */
export const issueContainerRegistryCredential = <ThrowOnError extends boolean = false>(options?: Options<IssueContainerRegistryCredentialData, ThrowOnError>) => {
    return (options?.client ?? client).post<IssueContainerRegistryCredentialResponses, IssueContainerRegistryCredentialErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/container-registries/default/credentials',
        ...options
    });
};

/**
 * List sandboxes
 */
export const listSandboxes = <ThrowOnError extends boolean = false>(options?: Options<ListSandboxesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSandboxesResponses, ListSandboxesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes',
        ...options
    });
};

/**
 * Create a sandbox
 */
export const createSandbox = <ThrowOnError extends boolean = false>(options: Options<CreateSandboxData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Batch get sandboxes by IDs
 */
export const batchGetSandboxes = <ThrowOnError extends boolean = false>(options: Options<BatchGetSandboxesData, ThrowOnError>) => {
    return (options.client ?? client).get<BatchGetSandboxesResponses, BatchGetSandboxesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/batch',
        ...options
    });
};

/**
 * Get a sandbox by ID
 */
export const getSandbox = <ThrowOnError extends boolean = false>(options: Options<GetSandboxData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSandboxResponses, GetSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/{id}',
        ...options
    });
};

/**
 * Terminate a sandbox
 * Terminates a sandbox. After this operation the sandbox cannot be used again.
 *
 */
export const terminateSandbox = <ThrowOnError extends boolean = false>(options: Options<TerminateSandboxData, ThrowOnError>) => {
    return (options.client ?? client).post<TerminateSandboxResponses, TerminateSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/{id}/terminate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Wait for a sandbox to reach a terminal status
 */
export const waitForSandbox = <ThrowOnError extends boolean = false>(options: Options<WaitForSandboxData, ThrowOnError>) => {
    return (options.client ?? client).post<WaitForSandboxResponses, WaitForSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/{id}/wait',
        ...options
    });
};

/**
 * List snapshots
 */
export const listSnapshots = <ThrowOnError extends boolean = false>(options?: Options<ListSnapshotsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSnapshotsResponses, ListSnapshotsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots',
        ...options
    });
};

/**
 * Create a snapshot for a container image
 */
export const createSnapshot = <ThrowOnError extends boolean = false>(options: Options<CreateSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateSnapshotResponses, CreateSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Batch get snapshots by IDs
 */
export const batchGetSnapshots = <ThrowOnError extends boolean = false>(options: Options<BatchGetSnapshotsData, ThrowOnError>) => {
    return (options.client ?? client).get<BatchGetSnapshotsResponses, BatchGetSnapshotsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/batch',
        ...options
    });
};

/**
 * Get a snapshot by ID
 */
export const getSnapshot = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSnapshotResponses, GetSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/{id}',
        ...options
    });
};

/**
 * Retire a snapshot
 * Retires the snapshot. Once retired, the snapshot can no longer be used to create new sandboxes, and it is eventually deleted, provided no sandbox still references it.
 *
 */
export const retireSnapshot = <ThrowOnError extends boolean = false>(options: Options<RetireSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).post<RetireSnapshotResponses, RetireSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/{id}/retire',
        ...options
    });
};

/**
 * Get a snapshot by alias
 */
export const getSnapshotByAlias = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotByAliasData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSnapshotByAliasResponses, GetSnapshotByAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/@{alias}',
        ...options
    });
};

/**
 * List a snapshot's aliases
 */
export const listSnapshotAliases = <ThrowOnError extends boolean = false>(options: Options<ListSnapshotAliasesData, ThrowOnError>) => {
    return (options.client ?? client).get<ListSnapshotAliasesResponses, ListSnapshotAliasesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/{snapshot_id}/aliases',
        ...options
    });
};

/**
 * Assign an alias to a snapshot
 * Points the alias at the snapshot. If an alias of the same name already exists in the project, it is repointed at this snapshot (an upsert).
 *
 */
export const aliasSnapshot = <ThrowOnError extends boolean = false>(options: Options<AliasSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).post<AliasSnapshotResponses, AliasSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/{snapshot_id}/aliases',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a snapshot alias
 * Deletes the alias in the caller's project. Idempotent: succeeds whether or not the alias exists.
 *
 */
export const deleteSnapshotAlias = <ThrowOnError extends boolean = false>(options: Options<DeleteSnapshotAliasData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteSnapshotAliasResponses, DeleteSnapshotAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshot-aliases/{alias}',
        ...options
    });
};
