// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AliasSnapshotData, AliasSnapshotErrors, AliasSnapshotResponses, AuthorizeData, AuthorizeErrors, AuthorizeResponses, BatchGetSandboxesData, BatchGetSandboxesErrors, BatchGetSandboxesResponses, BatchGetSnapshotsData, BatchGetSnapshotsErrors, BatchGetSnapshotsResponses, CreateSandboxData, CreateSandboxErrors, CreateSandboxResponses, CreateSnapshotData, CreateSnapshotErrors, CreateSnapshotResponses, DeleteSandboxData, DeleteSandboxErrors, DeleteSandboxResponses, DeleteSnapshotAliasByAliasData, DeleteSnapshotAliasByAliasErrors, DeleteSnapshotAliasByAliasResponses, DeleteSnapshotAliasData, DeleteSnapshotAliasErrors, DeleteSnapshotAliasResponses, DeleteSnapshotByAliasData, DeleteSnapshotByAliasErrors, DeleteSnapshotByAliasResponses, DeleteSnapshotData, DeleteSnapshotErrors, DeleteSnapshotResponses, GetSandboxData, GetSandboxErrors, GetSandboxResponses, GetSnapshotAliasByAliasData, GetSnapshotAliasByAliasErrors, GetSnapshotAliasByAliasResponses, GetSnapshotAliasData, GetSnapshotAliasErrors, GetSnapshotAliasResponses, GetSnapshotByAliasData, GetSnapshotByAliasErrors, GetSnapshotByAliasResponses, GetSnapshotData, GetSnapshotErrors, GetSnapshotResponses, IssueContainerRegistryCredentialData, IssueContainerRegistryCredentialErrors, IssueContainerRegistryCredentialResponses, ListSandboxesData, ListSandboxesErrors, ListSandboxesResponses, ListSnapshotsData, ListSnapshotsErrors, ListSnapshotsResponses, StopSandboxData, StopSandboxErrors, StopSandboxResponses, WaitForSandboxData, WaitForSandboxErrors, WaitForSandboxResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authorize access to a project or container registry project
 */
export const authorize = <ThrowOnError extends boolean = false>(options: Options<AuthorizeData, ThrowOnError>) => {
    return (options.client ?? client).post<AuthorizeResponses, AuthorizeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/authorize',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Issue a container registry credential for the authenticated user
 * Returns credentials (username, password, registry URL) for authenticating with the container registry. The registry URL includes the user's namespace path derived from their project ID.
 *
 */
export const issueContainerRegistryCredential = <ThrowOnError extends boolean = false>(options?: Options<IssueContainerRegistryCredentialData, ThrowOnError>) => {
    return (options?.client ?? client).post<IssueContainerRegistryCredentialResponses, IssueContainerRegistryCredentialErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/container-registries/default/credentials',
        ...options
    });
};

/**
 * List sandboxes
 */
export const listSandboxes = <ThrowOnError extends boolean = false>(options?: Options<ListSandboxesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSandboxesResponses, ListSandboxesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes',
        ...options
    });
};

/**
 * Create a sandbox
 */
export const createSandbox = <ThrowOnError extends boolean = false>(options: Options<CreateSandboxData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Batch get sandboxes by IDs
 */
export const batchGetSandboxes = <ThrowOnError extends boolean = false>(options: Options<BatchGetSandboxesData, ThrowOnError>) => {
    return (options.client ?? client).get<BatchGetSandboxesResponses, BatchGetSandboxesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/batch',
        ...options
    });
};

/**
 * Delete a sandbox
 */
export const deleteSandbox = <ThrowOnError extends boolean = false>(options: Options<DeleteSandboxData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteSandboxResponses, DeleteSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/{id}',
        ...options
    });
};

/**
 * Get a sandbox by ID
 */
export const getSandbox = <ThrowOnError extends boolean = false>(options: Options<GetSandboxData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSandboxResponses, GetSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/{id}',
        ...options
    });
};

/**
 * Stop a sandbox
 */
export const stopSandbox = <ThrowOnError extends boolean = false>(options: Options<StopSandboxData, ThrowOnError>) => {
    return (options.client ?? client).post<StopSandboxResponses, StopSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/{id}/stop',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Wait for a sandbox to reach a terminal status
 */
export const waitForSandbox = <ThrowOnError extends boolean = false>(options: Options<WaitForSandboxData, ThrowOnError>) => {
    return (options.client ?? client).post<WaitForSandboxResponses, WaitForSandboxErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/sandboxes/{id}/wait',
        ...options
    });
};

/**
 * List snapshots
 */
export const listSnapshots = <ThrowOnError extends boolean = false>(options?: Options<ListSnapshotsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSnapshotsResponses, ListSnapshotsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots',
        ...options
    });
};

/**
 * Create a snapshot for a container image
 */
export const createSnapshot = <ThrowOnError extends boolean = false>(options: Options<CreateSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateSnapshotResponses, CreateSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Batch get snapshots by IDs
 */
export const batchGetSnapshots = <ThrowOnError extends boolean = false>(options: Options<BatchGetSnapshotsData, ThrowOnError>) => {
    return (options.client ?? client).get<BatchGetSnapshotsResponses, BatchGetSnapshotsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/batch',
        ...options
    });
};

/**
 * Delete a snapshot
 */
export const deleteSnapshot = <ThrowOnError extends boolean = false>(options: Options<DeleteSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteSnapshotResponses, DeleteSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/{id}',
        ...options
    });
};

/**
 * Get a snapshot by ID
 */
export const getSnapshot = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSnapshotResponses, GetSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/{id}',
        ...options
    });
};

/**
 * Delete a snapshot by alias
 */
export const deleteSnapshotByAlias = <ThrowOnError extends boolean = false>(options: Options<DeleteSnapshotByAliasData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteSnapshotByAliasResponses, DeleteSnapshotByAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/@{alias}',
        ...options
    });
};

/**
 * Get a snapshot by alias
 */
export const getSnapshotByAlias = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotByAliasData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSnapshotByAliasResponses, GetSnapshotByAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/@{alias}',
        ...options
    });
};

/**
 * Assign an alias to a snapshot
 */
export const aliasSnapshot = <ThrowOnError extends boolean = false>(options: Options<AliasSnapshotData, ThrowOnError>) => {
    return (options.client ?? client).post<AliasSnapshotResponses, AliasSnapshotErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshots/{snapshot_id}/aliases',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a snapshot alias by ID
 */
export const deleteSnapshotAlias = <ThrowOnError extends boolean = false>(options: Options<DeleteSnapshotAliasData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteSnapshotAliasResponses, DeleteSnapshotAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshot-aliases/{id}',
        ...options
    });
};

/**
 * Get a snapshot alias by ID
 */
export const getSnapshotAlias = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotAliasData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSnapshotAliasResponses, GetSnapshotAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshot-aliases/{id}',
        ...options
    });
};

/**
 * Delete a snapshot alias by alias name
 */
export const deleteSnapshotAliasByAlias = <ThrowOnError extends boolean = false>(options: Options<DeleteSnapshotAliasByAliasData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteSnapshotAliasByAliasResponses, DeleteSnapshotAliasByAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshot-aliases/@{alias}',
        ...options
    });
};

/**
 * Get a snapshot alias by alias name
 */
export const getSnapshotAliasByAlias = <ThrowOnError extends boolean = false>(options: Options<GetSnapshotAliasByAliasData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSnapshotAliasByAliasResponses, GetSnapshotAliasByAliasErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/snapshot-aliases/@{alias}',
        ...options
    });
};
