// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type Sandbox = {
    /**
     * Short identifier (6–8 characters).
     */
    id: string;
    project_id: string;
    status: 'created' | 'starting' | 'running' | 'stopping' | 'stopped';
    ephemeral: boolean;
    cluster_name: string;
    /**
     * The snapshot the sandbox boots from.
     */
    source_snapshot_id: string;
    /**
     * The snapshot created when the sandbox stopped.
     */
    snapshot_id?: string | null;
    /**
     * CPU allocation in millicpu.
     */
    millicpu: number;
    gpu: number;
    memory_bytes: number;
    disk_bytes: number;
    agent_version: string;
    agent_type: string;
    agent_token: string;
    agent_url: string;
    created_at: string;
    start_requested_at: string | null;
    start_type: 'resume' | 'cold_start' | null;
    started_at: string | null;
    stop_requested_at: string | null;
    requested_stop_type: 'shutdown' | 'hibernate' | null;
    stopped_at: string | null;
    stop_reason: 'start_failed' | 'out_of_capacity' | 'shutdown' | 'hibernated' | 'crashed' | 'oom_killed' | 'evicted' | 'node_lost' | 'cluster_lost' | null;
    specs_updated_at: string | null;
    recovery_status: 'pending' | 'recovered' | 'canceled' | 'unrecoverable' | null;
    recovery_started_at: string | null;
    recovery_finished_at: string | null;
    updated_at: string;
};

export type Snapshot = {
    id: string;
    project_id: string;
    byte_size: number;
    protected: boolean;
    optimized: boolean;
    includes_memory_snapshot: boolean;
    created_at: string;
    optimized_at: string | null;
    updated_at: string;
};

export type SnapshotAlias = {
    id: string;
    snapshot_id: string;
    alias: string;
    created_at: string;
    updated_at: string;
};

export type ContainerRegistryCredential = {
    username: string;
    password: string;
    /**
     * Registry URL including the namespace path (e.g. registry.example.com/nbswy3dp).
     */
    registry_url: string;
    expired_at: string | null;
};

export type SandboxPage = {
    data: Array<Sandbox>;
    /**
     * Cursor for the next page; `null` when there are no more items.
     */
    next_cursor: string | null;
};

export type SnapshotPage = {
    data: Array<Snapshot>;
    /**
     * Cursor for the next page; `null` when there are no more items.
     */
    next_cursor: string | null;
};

export type _Error = {
    code: string;
    message: string;
    errors: Array<{
        parameter?: string;
        code?: string;
        message?: string;
        details?: {
            [key: string]: unknown;
        };
    }>;
};

export type AuthorizeData = {
    body: {
        /**
         * Project ID to authorize access to. Accepts a plain project ID (proj_* or ws_*) or a base32-encoded project ID from the container registry path.
         */
        project_id?: string;
    };
    path?: never;
    query?: never;
    url: '/authorize';
};

export type AuthorizeErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type AuthorizeError = AuthorizeErrors[keyof AuthorizeErrors];

export type AuthorizeResponses = {
    /**
     * Authorized.
     */
    204: void;
};

export type AuthorizeResponse = AuthorizeResponses[keyof AuthorizeResponses];

export type IssueContainerRegistryCredentialData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/container-registries/default/credentials';
};

export type IssueContainerRegistryCredentialErrors = {
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type IssueContainerRegistryCredentialError = IssueContainerRegistryCredentialErrors[keyof IssueContainerRegistryCredentialErrors];

export type IssueContainerRegistryCredentialResponses = {
    /**
     * Credential issued.
     */
    201: ContainerRegistryCredential;
};

export type IssueContainerRegistryCredentialResponse = IssueContainerRegistryCredentialResponses[keyof IssueContainerRegistryCredentialResponses];

export type ListSandboxesData = {
    body?: never;
    path?: never;
    query?: {
        project_id?: string;
        limit?: number;
        /**
         * Sandbox ID returned as `next_cursor` from a previous page.
         */
        cursor?: string;
    };
    url: '/sandboxes';
};

export type ListSandboxesErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type ListSandboxesError = ListSandboxesErrors[keyof ListSandboxesErrors];

export type ListSandboxesResponses = {
    /**
     * Paginated list of sandboxes.
     */
    200: SandboxPage;
};

export type ListSandboxesResponse = ListSandboxesResponses[keyof ListSandboxesResponses];

export type CreateSandboxData = {
    body: {
        /**
         * Sandbox ID (6–8 characters). Generated if not provided.
         */
        id?: string;
        /**
         * ID of the snapshot to use. One of snapshot_id or snapshot_alias is required.
         *
         */
        snapshot_id?: string;
        /**
         * Alias of the snapshot to use. One of snapshot_id or snapshot_alias is required.
         *
         */
        snapshot_alias?: string;
        ephemeral?: boolean;
        /**
         * Whether to automatically start the sandbox once created.
         */
        autostart?: boolean;
        /**
         * CPU allocation in millicpu. Must be > 0 and a multiple of 250.
         */
        millicpu: number;
        /**
         * Memory allocation in bytes. Must be > 0.
         */
        memory_bytes: number;
        /**
         * Disk allocation in bytes. Must be > 0.
         */
        disk_bytes: number;
    };
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type CreateSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type CreateSandboxError = CreateSandboxErrors[keyof CreateSandboxErrors];

export type CreateSandboxResponses = {
    /**
     * Sandbox created.
     */
    201: Sandbox;
};

export type CreateSandboxResponse = CreateSandboxResponses[keyof CreateSandboxResponses];

export type BatchGetSandboxesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * List of sandbox IDs. Maximum 100, no duplicates.
         */
        'ids[]': Array<string>;
    };
    url: '/sandboxes/batch';
};

export type BatchGetSandboxesErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type BatchGetSandboxesError = BatchGetSandboxesErrors[keyof BatchGetSandboxesErrors];

export type BatchGetSandboxesResponses = {
    /**
     * List of sandboxes (preserves request order; missing IDs are omitted).
     */
    200: Array<Sandbox>;
};

export type BatchGetSandboxesResponse = BatchGetSandboxesResponses[keyof BatchGetSandboxesResponses];

export type DeleteSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox ID (6–8 characters).
         */
        id: string;
    };
    query?: never;
    url: '/sandboxes/{id}';
};

export type DeleteSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type DeleteSandboxError = DeleteSandboxErrors[keyof DeleteSandboxErrors];

export type DeleteSandboxResponses = {
    /**
     * Sandbox deleted.
     */
    204: void;
};

export type DeleteSandboxResponse = DeleteSandboxResponses[keyof DeleteSandboxResponses];

export type GetSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox ID (6–8 characters).
         */
        id: string;
    };
    query?: never;
    url: '/sandboxes/{id}';
};

export type GetSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSandboxError = GetSandboxErrors[keyof GetSandboxErrors];

export type GetSandboxResponses = {
    /**
     * Sandbox.
     */
    200: Sandbox;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type StopSandboxData = {
    body?: {
        /**
         * How to stop the sandbox.
         */
        stop_type?: 'shutdown' | 'hibernate';
    };
    path: {
        /**
         * Sandbox ID (6–8 characters).
         */
        id: string;
    };
    query?: never;
    url: '/sandboxes/{id}/stop';
};

export type StopSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type StopSandboxError = StopSandboxErrors[keyof StopSandboxErrors];

export type StopSandboxResponses = {
    /**
     * Sandbox with updated status.
     */
    200: Sandbox;
};

export type StopSandboxResponse = StopSandboxResponses[keyof StopSandboxResponses];

export type WaitForSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox ID (6–8 characters).
         */
        id: string;
    };
    query?: never;
    url: '/sandboxes/{id}/wait';
};

export type WaitForSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type WaitForSandboxError = WaitForSandboxErrors[keyof WaitForSandboxErrors];

export type WaitForSandboxResponses = {
    /**
     * Sandbox at terminal status.
     */
    200: Sandbox;
};

export type WaitForSandboxResponse = WaitForSandboxResponses[keyof WaitForSandboxResponses];

export type ListSnapshotsData = {
    body?: never;
    path?: never;
    query?: {
        project_id?: string;
        limit?: number;
        /**
         * Snapshot ID returned as `next_cursor` from a previous page.
         */
        cursor?: string;
    };
    url: '/snapshots';
};

export type ListSnapshotsErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
    /**
     * Paginated list of snapshots.
     */
    200: SnapshotPage;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type CreateSnapshotData = {
    body: {
        /**
         * Container image reference. Parsed as `[registry/][repository/]name[:tag]`, using Docker Hub and `latest` as defaults when omitted.
         *
         */
        image: string;
        /**
         * Expected image architecture.
         */
        architecture?: 'amd64' | 'arm64';
    };
    path?: never;
    query?: never;
    url: '/snapshots';
};

export type CreateSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type CreateSnapshotError = CreateSnapshotErrors[keyof CreateSnapshotErrors];

export type CreateSnapshotResponses = {
    /**
     * Snapshot created.
     */
    201: Snapshot;
};

export type CreateSnapshotResponse = CreateSnapshotResponses[keyof CreateSnapshotResponses];

export type BatchGetSnapshotsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * List of snapshot UUIDs. Maximum 100, no duplicates.
         */
        'ids[]': Array<string>;
    };
    url: '/snapshots/batch';
};

export type BatchGetSnapshotsErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type BatchGetSnapshotsError = BatchGetSnapshotsErrors[keyof BatchGetSnapshotsErrors];

export type BatchGetSnapshotsResponses = {
    /**
     * List of snapshots (preserves request order; missing IDs are omitted).
     */
    200: Array<Snapshot>;
};

export type BatchGetSnapshotsResponse = BatchGetSnapshotsResponses[keyof BatchGetSnapshotsResponses];

export type DeleteSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/snapshots/{id}';
};

export type DeleteSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type DeleteSnapshotError = DeleteSnapshotErrors[keyof DeleteSnapshotErrors];

export type DeleteSnapshotResponses = {
    /**
     * Snapshot deleted.
     */
    204: void;
};

export type DeleteSnapshotResponse = DeleteSnapshotResponses[keyof DeleteSnapshotResponses];

export type GetSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/snapshots/{id}';
};

export type GetSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSnapshotError = GetSnapshotErrors[keyof GetSnapshotErrors];

export type GetSnapshotResponses = {
    /**
     * Snapshot.
     */
    200: Snapshot;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type DeleteSnapshotByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/snapshots/@{alias}';
};

export type DeleteSnapshotByAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type DeleteSnapshotByAliasError = DeleteSnapshotByAliasErrors[keyof DeleteSnapshotByAliasErrors];

export type DeleteSnapshotByAliasResponses = {
    /**
     * Snapshot deleted.
     */
    204: void;
};

export type DeleteSnapshotByAliasResponse = DeleteSnapshotByAliasResponses[keyof DeleteSnapshotByAliasResponses];

export type GetSnapshotByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/snapshots/@{alias}';
};

export type GetSnapshotByAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSnapshotByAliasError = GetSnapshotByAliasErrors[keyof GetSnapshotByAliasErrors];

export type GetSnapshotByAliasResponses = {
    /**
     * Snapshot.
     */
    200: Snapshot;
};

export type GetSnapshotByAliasResponse = GetSnapshotByAliasResponses[keyof GetSnapshotByAliasResponses];

export type AliasSnapshotData = {
    body: {
        alias: string;
    };
    path: {
        snapshot_id: string;
    };
    query?: never;
    url: '/snapshots/{snapshot_id}/aliases';
};

export type AliasSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type AliasSnapshotError = AliasSnapshotErrors[keyof AliasSnapshotErrors];

export type AliasSnapshotResponses = {
    /**
     * Alias assigned.
     */
    204: void;
};

export type AliasSnapshotResponse = AliasSnapshotResponses[keyof AliasSnapshotResponses];

export type DeleteSnapshotAliasData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/snapshot-aliases/{id}';
};

export type DeleteSnapshotAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type DeleteSnapshotAliasError = DeleteSnapshotAliasErrors[keyof DeleteSnapshotAliasErrors];

export type DeleteSnapshotAliasResponses = {
    /**
     * Snapshot alias deleted.
     */
    204: void;
};

export type DeleteSnapshotAliasResponse = DeleteSnapshotAliasResponses[keyof DeleteSnapshotAliasResponses];

export type GetSnapshotAliasData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/snapshot-aliases/{id}';
};

export type GetSnapshotAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSnapshotAliasError = GetSnapshotAliasErrors[keyof GetSnapshotAliasErrors];

export type GetSnapshotAliasResponses = {
    /**
     * Snapshot alias.
     */
    200: SnapshotAlias;
};

export type GetSnapshotAliasResponse = GetSnapshotAliasResponses[keyof GetSnapshotAliasResponses];

export type DeleteSnapshotAliasByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/snapshot-aliases/@{alias}';
};

export type DeleteSnapshotAliasByAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type DeleteSnapshotAliasByAliasError = DeleteSnapshotAliasByAliasErrors[keyof DeleteSnapshotAliasByAliasErrors];

export type DeleteSnapshotAliasByAliasResponses = {
    /**
     * Snapshot alias deleted.
     */
    204: void;
};

export type DeleteSnapshotAliasByAliasResponse = DeleteSnapshotAliasByAliasResponses[keyof DeleteSnapshotAliasByAliasResponses];

export type GetSnapshotAliasByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/snapshot-aliases/@{alias}';
};

export type GetSnapshotAliasByAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSnapshotAliasByAliasError = GetSnapshotAliasByAliasErrors[keyof GetSnapshotAliasByAliasErrors];

export type GetSnapshotAliasByAliasResponses = {
    /**
     * Snapshot alias.
     */
    200: SnapshotAlias;
};

export type GetSnapshotAliasByAliasResponse = GetSnapshotAliasByAliasResponses[keyof GetSnapshotAliasByAliasResponses];
