// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/v1` | (string & {});
};

/**
 * User-defined key-value labels (both keys and values are strings).
 */
export type Tags = {
    [key: string]: string;
};

export type Sandbox = {
    /**
     * The sandbox's unique identifier.
     */
    id: string;
    organization_id: string | null;
    project_id: string;
    status: 'starting' | 'running' | 'terminating' | 'terminated' | 'failed_to_start' | 'recovering' | 'unrecovered';
    /**
     * The snapshot the sandbox boots from. The snapshot produced when the sandbox terminates is aliased as `sandbox:<sandbox id>`.
     *
     */
    snapshot_id: string;
    /**
     * CPU allocation in cores.
     */
    cpu: number;
    /**
     * Memory allocation in bytes.
     */
    memory_bytes: number;
    /**
     * Connection details for the in-sandbox agent.
     */
    agent: {
        version: string | null;
        /**
         * Null unless the sandbox is running.
         */
        token: string | null;
        /**
         * Null unless the sandbox is running.
         */
        url: string | null;
    };
    /**
     * Seconds after creation before the sandbox is automatically terminated. Null disables automatic termination.
     *
     */
    ttl: number | null;
    tags: Tags;
    /**
     * The termination policy, or null for an ephemeral sandbox (no snapshot is taken and it is deleted on termination).
     *
     */
    termination_policy: TerminationPolicy | null;
    created_at: string;
    started_at: string | null;
    terminated_at: string | null;
    status_reason: 'cold_start_requested' | 'restore_requested' | 'cold_started' | 'restored' | 'out_of_capacity' | 'internal_error' | 'autoterminated' | 'termination_requested' | 'crashed' | 'oom_killed' | 'evicted' | 'node_lost' | 'cluster_lost';
    resized_at: string | null;
    recovery_at: string | null;
    updated_at: string;
};

/**
 * The policy applied when a sandbox terminates.
 */
export type TerminationPolicy = {
    snapshot: TerminationSnapshot;
};

/**
 * The snapshot captured when a sandbox terminates.
 */
export type TerminationSnapshot = {
    /**
     * Aliases to apply to the produced snapshot.
     */
    aliases?: Array<string>;
    /**
     * Seconds after which the snapshot produced on termination expires. Must be > 0. Omit to keep the snapshot indefinitely.
     *
     */
    ttl?: number;
    tags?: Tags;
};

export type Snapshot = {
    id: string;
    organization_id: string | null;
    project_id: string;
    byte_size: number;
    tags: Tags;
    /**
     * Seconds after creation before the snapshot is automatically retired, or null if it is kept indefinitely.
     *
     */
    ttl: number | null;
    /**
     * Whether the snapshot includes a memory snapshot.
     */
    memory: boolean;
    created_at: string;
    /**
     * When the snapshot was retired, or null if it is still active. A retired snapshot can no longer be used to create new sandboxes and is eventually deleted.
     *
     */
    retired_at: string | null;
    updated_at: string;
};

export type SnapshotAlias = {
    snapshot_id: string;
    alias: string;
    created_at: string;
};

export type ContainerRegistryCredential = {
    username: string;
    password: string;
    /**
     * Registry URL including the namespace path (e.g. registry.example.com/nbswy3dp).
     */
    registry_url: string;
    expired_at: string | null;
};

export type SandboxPage = {
    data: Array<Sandbox>;
    /**
     * Cursor for the next page; `null` when there are no more items.
     */
    next_cursor: string | null;
};

export type SnapshotPage = {
    data: Array<Snapshot>;
    /**
     * Cursor for the next page; `null` when there are no more items.
     */
    next_cursor: string | null;
};

export type _Error = {
    code: string;
    message: string;
    errors: Array<{
        parameter?: string;
        code?: string;
        message?: string;
        details?: {
            [key: string]: unknown;
        };
    }>;
};

export type AuthorizeData = {
    body: {
        /**
         * Project ID to authorize access to. Accepts a plain project ID (proj_* or ws_*) or a base32-encoded project ID from the container registry path.
         */
        project_id?: string;
    };
    path?: never;
    query?: never;
    url: '/authorize';
};

export type AuthorizeErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type AuthorizeError = AuthorizeErrors[keyof AuthorizeErrors];

export type AuthorizeResponses = {
    /**
     * Authorized.
     */
    204: void;
};

export type AuthorizeResponse = AuthorizeResponses[keyof AuthorizeResponses];

export type IssueContainerRegistryCredentialData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/container-registries/default/credentials';
};

export type IssueContainerRegistryCredentialErrors = {
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type IssueContainerRegistryCredentialError = IssueContainerRegistryCredentialErrors[keyof IssueContainerRegistryCredentialErrors];

export type IssueContainerRegistryCredentialResponses = {
    /**
     * Credential issued.
     */
    201: ContainerRegistryCredential;
};

export type IssueContainerRegistryCredentialResponse = IssueContainerRegistryCredentialResponses[keyof IssueContainerRegistryCredentialResponses];

export type ListSandboxesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        /**
         * Sandbox ID returned as `next_cursor` from a previous page.
         */
        cursor?: string;
        /**
         * Filter by status; matches sandboxes in any of the given statuses.
         */
        'statuses[]'?: Array<'starting' | 'running' | 'terminating' | 'terminated' | 'failed_to_start' | 'recovering' | 'unrecovered'>;
        /**
         * Filter by tags; matches sandboxes whose tags contain all given pairs.
         */
        tags?: Tags;
    };
    url: '/sandboxes';
};

export type ListSandboxesErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type ListSandboxesError = ListSandboxesErrors[keyof ListSandboxesErrors];

export type ListSandboxesResponses = {
    /**
     * Paginated list of sandboxes.
     */
    200: SandboxPage;
};

export type ListSandboxesResponse = ListSandboxesResponses[keyof ListSandboxesResponses];

export type CreateSandboxData = {
    body: {
        /**
         * ID of the snapshot to use. One of snapshot_id or snapshot_alias is required.
         *
         */
        snapshot_id?: string;
        /**
         * Alias of the snapshot to use. One of snapshot_id or snapshot_alias is required.
         *
         */
        snapshot_alias?: string;
        /**
         * CPU allocation in cores. Defaults to 1 when omitted.
         *
         */
        cpu?: number;
        /**
         * Memory allocation in bytes. Must be between 1 GB and 8 GB per requested CPU. Defaults to 2 GB when omitted.
         *
         */
        memory_bytes?: number;
        /**
         * Seconds after creation before the sandbox is automatically terminated. Must be > 0. Omit to disable automatic termination.
         *
         */
        ttl?: number;
        tags?: Tags;
        /**
         * The termination policy. Omit for an ephemeral sandbox (no snapshot, deleted on termination).
         *
         */
        termination_policy?: TerminationPolicy;
    };
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type CreateSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type CreateSandboxError = CreateSandboxErrors[keyof CreateSandboxErrors];

export type CreateSandboxResponses = {
    /**
     * Sandbox created.
     */
    201: Sandbox;
};

export type CreateSandboxResponse = CreateSandboxResponses[keyof CreateSandboxResponses];

export type BatchGetSandboxesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * List of sandbox IDs. Maximum 100, no duplicates.
         */
        'ids[]': Array<string>;
    };
    url: '/sandboxes/batch';
};

export type BatchGetSandboxesErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type BatchGetSandboxesError = BatchGetSandboxesErrors[keyof BatchGetSandboxesErrors];

export type BatchGetSandboxesResponses = {
    /**
     * List of sandboxes (preserves request order; missing IDs are omitted).
     */
    200: Array<Sandbox>;
};

export type BatchGetSandboxesResponse = BatchGetSandboxesResponses[keyof BatchGetSandboxesResponses];

export type GetSandboxData = {
    body?: never;
    path: {
        /**
         * The sandbox's unique identifier.
         */
        id: string;
    };
    query?: never;
    url: '/sandboxes/{id}';
};

export type GetSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSandboxError = GetSandboxErrors[keyof GetSandboxErrors];

export type GetSandboxResponses = {
    /**
     * Sandbox.
     */
    200: Sandbox;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type TerminateSandboxData = {
    body?: {
        /**
         * What this teardown snapshots, overriding the snapshot the sandbox's stored termination policy would take. Omit to keep the stored policy; null makes the teardown ephemeral (no snapshot).
         *
         */
        snapshot?: TerminationSnapshot | null;
    };
    path: {
        /**
         * The sandbox's unique identifier.
         */
        id: string;
    };
    query?: never;
    url: '/sandboxes/{id}/terminate';
};

export type TerminateSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type TerminateSandboxError = TerminateSandboxErrors[keyof TerminateSandboxErrors];

export type TerminateSandboxResponses = {
    /**
     * Sandbox with updated status.
     */
    200: Sandbox;
};

export type TerminateSandboxResponse = TerminateSandboxResponses[keyof TerminateSandboxResponses];

export type WaitForSandboxData = {
    body?: never;
    path: {
        /**
         * The sandbox's unique identifier.
         */
        id: string;
    };
    query?: never;
    url: '/sandboxes/{id}/wait';
};

export type WaitForSandboxErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type WaitForSandboxError = WaitForSandboxErrors[keyof WaitForSandboxErrors];

export type WaitForSandboxResponses = {
    /**
     * Sandbox at terminal status.
     */
    200: Sandbox;
};

export type WaitForSandboxResponse = WaitForSandboxResponses[keyof WaitForSandboxResponses];

export type ListSnapshotsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        /**
         * Snapshot ID returned as `next_cursor` from a previous page.
         */
        cursor?: string;
        /**
         * Filter by tags; matches snapshots whose tags contain all given pairs.
         */
        tags?: Tags;
        /**
         * When true, retired snapshots are excluded. Defaults to false.
         */
        exclude_retired?: boolean;
    };
    url: '/snapshots';
};

export type ListSnapshotsErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
    /**
     * Paginated list of snapshots.
     */
    200: SnapshotPage;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type CreateSnapshotData = {
    body: {
        /**
         * Container image reference. Parsed as `[registry/][repository/]name[:tag]`, using Docker Hub and `latest` as defaults when omitted.
         *
         */
        image: string;
        /**
         * Expected image architecture.
         */
        architecture?: 'amd64' | 'arm64';
        /**
         * Seconds after creation before the snapshot is automatically deleted. Omit to keep the snapshot indefinitely.
         *
         */
        ttl?: number;
        tags?: Tags;
    };
    path?: never;
    query?: never;
    url: '/snapshots';
};

export type CreateSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type CreateSnapshotError = CreateSnapshotErrors[keyof CreateSnapshotErrors];

export type CreateSnapshotResponses = {
    /**
     * Snapshot created.
     */
    201: Snapshot;
};

export type CreateSnapshotResponse = CreateSnapshotResponses[keyof CreateSnapshotResponses];

export type BatchGetSnapshotsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * List of snapshot UUIDs. Maximum 100, no duplicates.
         */
        'ids[]': Array<string>;
    };
    url: '/snapshots/batch';
};

export type BatchGetSnapshotsErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
};

export type BatchGetSnapshotsError = BatchGetSnapshotsErrors[keyof BatchGetSnapshotsErrors];

export type BatchGetSnapshotsResponses = {
    /**
     * List of snapshots (preserves request order; missing IDs are omitted).
     */
    200: Array<Snapshot>;
};

export type BatchGetSnapshotsResponse = BatchGetSnapshotsResponses[keyof BatchGetSnapshotsResponses];

export type GetSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/snapshots/{id}';
};

export type GetSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSnapshotError = GetSnapshotErrors[keyof GetSnapshotErrors];

export type GetSnapshotResponses = {
    /**
     * Snapshot.
     */
    200: Snapshot;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type RetireSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/snapshots/{id}/retire';
};

export type RetireSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type RetireSnapshotError = RetireSnapshotErrors[keyof RetireSnapshotErrors];

export type RetireSnapshotResponses = {
    /**
     * The retired snapshot.
     */
    200: Snapshot;
};

export type RetireSnapshotResponse = RetireSnapshotResponses[keyof RetireSnapshotResponses];

export type GetSnapshotByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/snapshots/@{alias}';
};

export type GetSnapshotByAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type GetSnapshotByAliasError = GetSnapshotByAliasErrors[keyof GetSnapshotByAliasErrors];

export type GetSnapshotByAliasResponses = {
    /**
     * Snapshot.
     */
    200: Snapshot;
};

export type GetSnapshotByAliasResponse = GetSnapshotByAliasResponses[keyof GetSnapshotByAliasResponses];

export type ListSnapshotAliasesData = {
    body?: never;
    path: {
        snapshot_id: string;
    };
    query?: never;
    url: '/snapshots/{snapshot_id}/aliases';
};

export type ListSnapshotAliasesErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type ListSnapshotAliasesError = ListSnapshotAliasesErrors[keyof ListSnapshotAliasesErrors];

export type ListSnapshotAliasesResponses = {
    /**
     * The snapshot's aliases.
     */
    200: Array<SnapshotAlias>;
};

export type ListSnapshotAliasesResponse = ListSnapshotAliasesResponses[keyof ListSnapshotAliasesResponses];

export type AliasSnapshotData = {
    body: {
        alias: string;
    };
    path: {
        snapshot_id: string;
    };
    query?: never;
    url: '/snapshots/{snapshot_id}/aliases';
};

export type AliasSnapshotErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type AliasSnapshotError = AliasSnapshotErrors[keyof AliasSnapshotErrors];

export type AliasSnapshotResponses = {
    /**
     * Alias assigned.
     */
    204: void;
};

export type AliasSnapshotResponse = AliasSnapshotResponses[keyof AliasSnapshotResponses];

export type DeleteSnapshotAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/snapshot-aliases/{alias}';
};

export type DeleteSnapshotAliasErrors = {
    /**
     * Bad request.
     */
    400: _Error;
    /**
     * Not authenticated.
     */
    401: _Error;
    /**
     * Not authorized.
     */
    403: _Error;
    /**
     * Resource not found.
     */
    404: _Error;
};

export type DeleteSnapshotAliasError = DeleteSnapshotAliasErrors[keyof DeleteSnapshotAliasErrors];

export type DeleteSnapshotAliasResponses = {
    /**
     * Alias deleted.
     */
    204: void;
};

export type DeleteSnapshotAliasResponse = DeleteSnapshotAliasResponses[keyof DeleteSnapshotAliasResponses];
