from typing import List, TypeAlias

from .preview_host_list_response_data_preview_hosts_item import PreviewHostListResponseDataPreviewHostsItem

from .preview_host_list_response_data_preview_hosts_item import PreviewHostListResponseDataPreviewHostsItem

__all__ = ['PreviewHostListResponseDataPreviewHosts']

PreviewHostListResponseDataPreviewHosts: TypeAlias = List[PreviewHostListResponseDataPreviewHostsItem]